version: '3.7'

services:

  counter_app:
    container_name: solana-gallery
    build:
      context: .
      dockerfile: Dockerfile
    image: solana-project
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true